const mongoose = require('mongoose');

const CategorySchema = new mongoose.Schema({
    // CategoryID is auto-generated by MongoDB as _id

    // CategoryName
    name: {
        type: String,
        required: true,
        unique: true, // Each category name should be unique
        trim: true
    }
}, { timestamps: true });

module.exports = mongoose.model('Category', CategorySchema);